on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

name: CI

jobs:
  install:
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build

  test:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm run test -- --coverage
      - uses: codecov/codecov-action@v3

  typecheck:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: $(npm bin)/tsc --noEmit

  check-formatting:
    name: check formatting
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: $(npm bin)/prettier --check .

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - install
      - build
      - test
      - check-formatting
      - typecheck
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Version package.json
        run: npm version ${{steps.tag.outputs.tag}}
      - name: Publish
        run: npm publish
