on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build

  test:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm run test -- --coverage

  typecheck:
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: $(npm bin)/tsc --noEmit

  check-formatting:
    name: check formatting
    needs: install
    runs-on: ubuntu-latest
    container: "node:16"
    steps:
      - uses: actions/checkout@v2
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: $(npm bin)/prettier --check .
